# Generated by Django 4.2.11 on 2025-02-05 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_appointments_delete_appointment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointments',
            options={'ordering': ['-sent_date'], 'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.AlterField(
            model_name='appointments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_user', to=settings.AUTH_USER_MODEL, to_field='email', unique=True),
        ),
        migrations.CreateModel(
            name='AcceptedAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_appointments', to='home.appointments', to_field='user')),
                ('first_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_first_name', to='home.appointments')),
                ('last_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_last_name', to='home.appointments')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_phone', to='home.appointments')),
            ],
        ),
    ]
