# Generated by Django 4.2.11 on 2025-02-05 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_alter_appointments_options_alter_appointments_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptedappointment',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_appointments', to='home.appointments'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_user', to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
    ]
