# Generated by Django 4.2.11 on 2025-02-05 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_acceptedappointment_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acceptedappointment',
            old_name='email',
            new_name='appointment',
        ),
        migrations.RemoveField(
            model_name='acceptedappointment',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='acceptedappointment',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='acceptedappointment',
            name='phone',
        ),
    ]
