# Generated by Django 4.2.11 on 2025-02-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_appointments_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='rejected',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='suspended',
        ),
        migrations.AddField(
            model_name='appointments',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Confirmed'), ('rejected', 'Cancelled')], default='pending', max_length=50),
        ),
    ]
