# Generated by Django 4.2.11 on 2025-02-05 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_appointments_accepted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejected_appointments', to='home.appointments')),
            ],
        ),
    ]
