# Generated by Django 4.2.11 on 2025-02-05 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rejectedappointment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acceptedappointment',
            options={'ordering': ['-date'], 'verbose_name': 'Accepted Appointment', 'verbose_name_plural': 'Accepted Appointments'},
        ),
    ]
