# Generated by Django 4.2.11 on 2025-02-05 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_acceptedappointment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='note',
            field=models.TextField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='rejectedappointment',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.appointments', to_field='note'),
        ),
    ]
