# Generated by Django 4.2.11 on 2025-02-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_appointments_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rejectedappointment',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='rejectedappointment',
            name='reason',
        ),
        migrations.AlterField(
            model_name='appointments',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='AcceptedAppointment',
        ),
        migrations.DeleteModel(
            name='RejectedAppointment',
        ),
    ]
