# Generated by Django 4.2.11 on 2025-02-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_rejectedappointment_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='checked_date',
            field=models.DateField(auto_now=True),
        ),
    ]
