# Generated by Django 4.2.11 on 2025-02-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_appointments_checked_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'در انتظار پاسخ'), ('accepted', 'تایید شده'), ('rejected', 'لغو  شده')], default='pending', max_length=50),
        ),
    ]
