# Generated by Django 5.1.5 on 2025-03-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='category',
            field=models.CharField(blank=True, choices=[('heart', 'قلب و عروق'), ('brain', 'اعصاب و روان'), ('surgery', 'جراح')], max_length=50),
        ),
        migrations.AddField(
            model_name='appointments',
            name='meet_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
